version: 2
updates:
- package-ecosystem: nuget
  directory: "/bansheeblog-backend"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Handlebars.Net
    versions:
    - 2.0.4
    - 2.0.5
    - 2.0.6
  - dependency-name: UAParser
    versions:
    - 3.1.44
  - dependency-name: Newtonsoft.Json
    versions:
    - 12.0.3
